# Generated by Django 3.1.7 on 2021-08-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldcoffee',
            name='instagram',
            field=models.CharField(default='Instagram handle', max_length=100),
        ),
    ]
