# Generated by Django 3.1.7 on 2021-08-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20210803_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='number_of_packages',
            field=models.IntegerField(default=1),
        ),
    ]
